services:
  - type: web
    name: super-manager-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        value: https://hpqmcdygbjdmvxfmvucf.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ENCRYPTION_SECRET
        sync: false
    healthCheckPath: /api/health
